var l=!0,p=null,t=!1;function x(){return function(){}}
(function(r){function d(){}function C(a,b,e){var o,f="mixpanel"===e?r:r[e];if(f&&!c.isArray(f))u.error(1,"You have already initialized "+e);else return o=new d,o.X(a,b,e),y=y||o.b("debug"),"undefined"!==typeof f&&o.W(f),o}function j(a){this.props={};this.z=t;this.name=a.cookie_name?"mp_"+a.cookie_name:"mp_"+a.token+"_mixpanel";this.load();this.R(a);this.va(a);this.save()}function D(){this.L="submit"}function z(){this.L="click"}function v(){}function A(){if(!A.ca)G=A.ca=l,c.a(w,function(a){a.V()})}
var y=t,G=t,c={},E=Array.prototype,B=Object.prototype,H=E.slice,I=B.toString,F=B.hasOwnProperty,s=window.console,J=window.navigator,m=window.document,n=J.userAgent,L={api_host:("https:"==m.location.protocol?"https://":"http://")+"api.mixpanel.com",cross_subdomain_cookie:l,cookie_name:"",loaded:x(),store_google:l,save_referrer:l,test:t,img:t,track_pageview:l,debug:t,track_links_timeout:300,cookie_expiration:365,upgrade:t,disable_cookie:t};(function(){var a=E.forEach,b=E.indexOf,e=Array.isArray,o={},
f=c.a=function(b,e,c){if(b!=p)if(a&&b.forEach===a)b.forEach(e,c);else if(b.length===+b.length)for(var f=0,d=b.length;f<d&&!(f in b&&e.call(c,b[f],f,b)===o);f++);else for(f in b)if(F.call(b,f)&&e.call(c,b[f],f,b)===o)break};c.extend=function(a){f(H.call(arguments,1),function(b){for(var e in b)void 0!==b[e]&&(a[e]=b[e])});return a};c.isArray=e||function(a){return"[object Array]"===I.call(a)};c.ja=function(a){try{return/^\s*\bfunction\b/.test(a)}catch(b){return t}};c.ha=function(a){return!(!a||!F.call(a,
"callee"))};c.k=function(a){return!a?[]:a.k?a.k():c.isArray(a)||c.ha(a)?H.call(a):c.xa(a)};c.xa=function(a){var b=[];if(a==p)return b;f(a,function(a){b[b.length]=a});return b};c.ya=function(a){return a};c.ga=function(a,e){var c=t;if(a==p)return c;if(b&&a.indexOf===b)return-1!=a.indexOf(e);f(a,function(a){if(c||(c=a===e))return o});return c};c.c=function(a,b){return-1!==a.indexOf(b)}})();c.H=function(a,b){a.prototype=new b;a.qa=b.prototype};c.f=function(a){return a===Object(a)&&!c.isArray(a)};c.da=
function(){return parseInt((new Date).getTime().toString().substring(0,10),10)};c.truncate=function(a,b){var e;"string"===typeof a?e=a.slice(0,b):c.isArray(a)?(e=[],c.a(a,function(a){e.push(c.truncate(a,b))})):c.f(a)?(e={},c.a(a,function(a,f){e[f]=c.truncate(a,b)})):e=a;return e};c.l=function(a){function b(a,c){var h="",g=0,k=g="",k=0,d=h,q=[],i=c[a];i&&"object"===typeof i&&"function"===typeof i.toJSON&&(i=i.toJSON(a));switch(typeof i){case "string":return e(i);case "number":return isFinite(i)?""+
i:"null";case "boolean":case "null":return""+i;case "object":if(!i)return"null";h+="    ";q=[];if("[object Array]"===I.apply(i)){k=i.length;for(g=0;g<k;g+=1)q[g]=b(g,i)||"null";return k=0===q.length?"[]":h?"[\n"+h+q.join(",\n"+h)+"\n"+d+"]":"["+q.join(",")+"]"}for(g in i)F.call(i,g)&&(k=b(g,i))&&q.push(e(g)+(h?": ":":")+k);return k=0===q.length?"{}":h?"{"+q.join(",")+""+d+"}":"{"+q.join(",")+"}"}}function e(a){var b=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
e={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};b.lastIndex=0;return b.test(a)?'"'+a.replace(b,function(a){var b=e[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}return b("",{"":a})};c.Z=function(a){var b,e,o,f,h=0,g=0,d="",d=[];if(!a)return a;a=c.wa(a);do b=a.charCodeAt(h++),e=a.charCodeAt(h++),o=a.charCodeAt(h++),f=b<<16|e<<8|o,b=f>>18&63,e=f>>12&63,o=f>>6&63,f&=63,d[g++]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(e)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(o)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(f);while(h<a.length);d=d.join("");switch(a.length%3){case 1:d=d.slice(0,-2)+"==";break;case 2:d=d.slice(0,-1)+"="}return d};c.wa=function(a){var a=(a+"").replace(/\r\n/g,"\n").replace(/\r/g,"\n"),b="",e,c,f=0,d;e=c=0;f=a.length;for(d=0;d<f;d++){var g=a.charCodeAt(d),k=p;
128>g?c++:k=127<g&&2048>g?String.fromCharCode(g>>6|192,g&63|128):String.fromCharCode(g>>12|224,g>>6&63|128,g&63|128);k!==p&&(c>e&&(b+=a.substring(e,c)),b+=k,e=c=d+1)}c>e&&(b+=a.substring(e,a.length));return b};c.U=function(){function a(){function a(b,e){var c,o=0;for(c=0;c<e.length;c++)o|=d[c]<<8*c;return b^o}var b,c,d=[],g=0;for(b=0;b<n.length;b++)c=n.charCodeAt(b),d.unshift(c&255),4<=d.length&&(g=a(g,d),d=[]);0<d.length&&(g=a(g,d));return g.toString(16)}function b(){for(var a=1*new Date,b=0;a==
1*new Date;)b++;return a.toString(16)+b.toString(16)}return function(){var e=(screen.height*screen.width).toString(16);return b()+"-"+Math.random().toString(16).replace(".","")+"-"+a()+"-"+e+"-"+b()}}();c.ia=function(){return/(google web preview|baiduspider|yandexbot)/i.test(n)?l:t};c.T=function(a){var b,e,o,f=[];"undefined"===typeof b&&(b="&");c.a(a,function(a,b){e=encodeURIComponent(a.toString());o=encodeURIComponent(b);f[f.length]=o+"="+e});return f.join(b)};c.F=function(a,b){var b=b.replace(/[\[]/,
"\\[").replace(/[\]]/,"\\]"),e=RegExp("[\\?&]"+b+"=([^&#]*)").exec(a);return e===p||e&&"string"!==typeof e[1]&&e[1].length?"":decodeURIComponent(e[1]).replace(/\+/g," ")};c.cookie={get:function(a){for(var a=a+"=",b=m.cookie.split(";"),e=0;e<b.length;e++){for(var c=b[e];" "==c.charAt(0);)c=c.substring(1,c.length);if(0==c.indexOf(a))return decodeURIComponent(c.substring(a.length,c.length))}return p},eval:function(a){var b;try{b=eval("("+c.cookie.get(a)+")")||{}}catch(e){}return b},set:function(a,b,
c,o){var e;var f="",d="";o&&(e=(f=(f=m.location.hostname.match(/[a-z0-9][a-z0-9\-]+\.[a-z\.]{2,6}$/i))?f[0]:"")?"; domain=."+f:"",f=e);c&&(d=new Date,d.setTime(d.getTime()+864E5*c),d="; expires="+d.toGMTString());m.cookie=a+"="+encodeURIComponent(b)+d+"; path=/"+f},remove:function(a,b){c.cookie.set(a,"",-1,b)}};c.N=function(){function a(a){function c(b){return a[h](b)}a[h]=b;c[f]=l;return c}function b(a){if(a=a||e(window.event)){var b=l,d=this.j[a.type],f;for(f in d)if(!Object.prototype[f])this.h=
d[f],c.ja(this.h)&&this.h(a)===t&&(b=t);if(this.h)this.h=p;return b}}function e(a){if(a)a.preventDefault=e.preventDefault,a.stopPropagation=e.stopPropagation;return a}var d,f="__cbefHandler",h="__handleEvent";d=function(b,c,e,h){if(b)if(b.addEventListener&&!h)b.addEventListener(c,e,t);else{if(!e.v)e.v=d.G++;if(!b.j)b.j={};var h=b.j[c],i="on"+c;h||(h=b.j[c]={});b[i]&&!b[i][f]?(h[d.G++]=b[i],b[i]=a(b)):b[i]||(b[i]=a(b));h[e.v]=e}else u.error(8,"No valid element provided to register_event")};d.G=1;e.preventDefault=
function(){this.returnValue=t};e.stopPropagation=function(){this.cancelBubble=l};return d}();c.ba=function(){return function(a){if(!m.getElementsByTagName)return[];for(var a=a.split(" "),b=Array(m),c=0;c<a.length;c++)if(token=a[c].replace(/^\s+/,"").replace(/\s+$/,""),-1<token.indexOf("#")){var d=token.split("#"),f=d[0],b=m.getElementById(d[1]);if(f&&b.nodeName.toLowerCase()!=f)return[];b=Array(b)}else if(-1<token.indexOf(".")){var d=token.split("."),f=d[0],h=d[1];f||(f="*");for(var d=[],g=0,k=0;k<
b.length;k++){var j;j="*"==f?b[k].all?b[k].all:b[k].getElementsByTagName("*"):b[k].getElementsByTagName(f);for(var q=0;q<j.length;q++)d[g++]=j[q]}b=[];for(g=f=0;g<d.length;g++)d[g].className&&d[g].className.match(RegExp("\\b"+h+"\\b"))&&(b[f++]=d[g])}else if(token.match(/^(\w*)\[(\w+)([=~\|\^\$\*]?)=?"?([^\]"]*)"?\]$/)){var f=RegExp.$1,i=RegExp.$2,h=RegExp.$3,n=RegExp.$4;f||(f="*");d=[];for(k=g=0;k<b.length;k++){j="*"==f?b[k].all?b[k].all:b[k].getElementsByTagName("*"):b[k].getElementsByTagName(f);
for(q=0;q<j.length;q++)d[g++]=j[q]}b=[];f=0;switch(h){case "=":h=function(a){return a.getAttribute(i)==n};break;case "~":h=function(a){return a.getAttribute(i).match(RegExp("\\b"+n+"\\b"))};break;case "|":h=function(a){return a.getAttribute(i).match(RegExp("^"+n+"-?"))};break;case "^":h=function(a){return 0==a.getAttribute(i).indexOf(n)};break;case "$":h=function(a){return a.getAttribute(i).lastIndexOf(n)==a.getAttribute(i).length-n.length};break;case "*":h=function(a){return-1<a.getAttribute(i).indexOf(n)};
break;default:h=function(a){return a.getAttribute(i)}}b=[];for(g=f=0;g<d.length;g++)h(d[g])&&(b[f++]=d[g])}else{f=token;d=[];for(k=g=0;k<b.length;k++){j=b[k].getElementsByTagName(f);for(q=0;q<j.length;q++)d[g++]=j[q]}b=d}return b}}();c.info={aa:function(){var a="",b={};c.a("utm_source utm_medium utm_campaign utm_content utm_term".split(" "),function(e){a=c.F(m.URL,e);a.length&&(b[e]=a)});return b},ma:function(a){return 0===a.search("https?://(.*)google.([^/?]*)")?"google":0===a.search("https?://(.*)bing.com")?
"bing":0===a.search("https?://(.*)yahoo.com")?"yahoo":0===a.search("https?://(.*)duckduckgo.com")?"duckduckgo":p},na:function(a){var b=c.info.ma(a),e={};if(b!==p)e.$search_engine=b,a=c.F(a,"yahoo"!=b?"q":"p"),a.length&&(e.mp_keyword=a);return e},w:function(){var a=J.vendor||"";return window.opera?c.c(n,"Mini")?"Opera Mini":"Opera":c.c(n,"Chrome")?"Chrome":c.c(a,"Apple")?c.c(n,"Mobile")?"iOS Mobile":"Safari":c.c(n,"Android")?"Android Mobile":c.c(a,"KDE")?"Konqueror":c.c(n,"Firefox")?"Firefox":c.c(n,
"MSIE")?"Internet Explorer":c.c(n,"Gecko")?"Mozilla":""},K:function(){return/Windows/i.test(n)?"Windows":/iPhone/.test(n)?"iPhone":/Android/.test(n)?"Android":/Mac/i.test(n)?"Mac OS X":/X11/.test(n)||/Linux/.test(n)?"Linux":""},M:function(a){a=a.split("/");return 3<=a.length?a[2]:""},t:function(){return{$os:c.info.K(),$browser:c.info.w(),$referrer:m.referrer,$referring_domain:c.info.M(m.referrer)}},la:function(a){a={mp_page:a,mp_referrer:m.referrer,mp_browser:c.info.w(),mp_platform:c.info.K()};c.a(a,
x());return a}};var u={log:function(){if("undefined"!==typeof s&&s&&y)try{s.log.apply(s,arguments)}catch(a){s.log("<< MPLib >>"),c.a(arguments,function(a){s.log(a)}),s.log("<</ MPLib >>")}},error:function(a){if("undefined"!==typeof s&&s&&y){var b=c.k(arguments).slice(1),b=["Mixpanel Error ("+a+"): "].concat(b);try{s.error.apply(s,b)}catch(e){c.a(b,function(a){s.error(a)})}}}};v.prototype.i=x();v.prototype.q=x();v.prototype.o=x();v.prototype.s=function(a){this.I=a;return this};v.prototype.g=function(a,
b,e,d){var f=this,h=c.ba(a);if(0==h.length)u.error(7,"The DOM query ("+a+") returned 0 elements");else return c.a(h,function(a){c.N(a,this.L,function(a){var c={},g=f.i(e,this),h=f.I.b("track_links_timeout");f.q(a,this,c);window.setTimeout(f.P(d,g,c,l),h);f.I.g(b,g,f.P(d,g,c))})},this),l};v.prototype.P=function(a,b,c,d){var d=d||t,f=this;return function(){if(!c.$)c.$=l,a&&a(d,b)===t||f.o(b,c,d)}};v.prototype.i=function(a,b){return"function"===typeof a?a(b):c.extend({},a)};c.H(z,v);z.prototype.i=function(a,
b){var c=z.qa.i.apply(this,arguments);if(b.href)c.url=b.href;return c};z.prototype.q=function(a,b,c){c.J=2===a.which||a.metaKey||"_blank"===b.target;c.href=b.href;c.J||a.preventDefault()};z.prototype.o=function(a,b){b.J||setTimeout(function(){window.location=b.href},0)};c.H(D,v);D.prototype.q=function(a,b,c){c.element=b;a.preventDefault()};D.prototype.o=function(a,b){setTimeout(function(){b.element.submit()},0)};j.prototype.t=function(){return this.props};j.prototype.load=function(){if(!this.disabled){var a=
c.cookie.eval(this.name);a&&(this.props=c.extend({},a))}};j.prototype.va=function(a){var b=a.upgrade,e;if(b)e="mp_super_properties","string"===typeof b&&(e=b),b=c.cookie.eval(e),c.cookie.remove(e),c.cookie.remove(e,l),b&&(this.props=c.extend(this.props,b.all,b.events));if(!a.cookie_name&&"mixpanel"!==a.name&&(e="mp_"+a.token+"_"+a.name,b=c.cookie.eval(e)))c.cookie.remove(e),c.cookie.remove(e,l),this.d(b)};j.prototype.save=function(){this.disabled||c.cookie.set(this.name,c.l(this.props),this.r,this.A)};
j.prototype.remove=function(){c.cookie.remove(this.name,t);c.cookie.remove(this.name,l)};j.prototype.clear=function(){this.remove();this.props={}};j.prototype.d=function(a,b,e){return c.f(a)?("undefined"===typeof b&&(b="None"),this.r="undefined"===typeof e?this.B:e,c.a(a,function(a,c){if(!this.props[c]||this.props[c]===b)this.props[c]=a},this),this.save(),l):t};j.prototype.e=function(a,b){return c.f(a)?(this.r="undefined"===typeof b?this.B:b,c.extend(this.props,a),this.save(),l):t};j.prototype.u=
function(a){a in this.props&&(delete this.props[a],this.save())};j.prototype.ta=function(){if(!this.z)this.d(c.info.aa()),this.z=l};j.prototype.S=function(a){this.e(c.info.na(a))};j.prototype.ua=function(a){this.d({$initial_referrer:a||"$direct",$initial_referring_domain:c.info.M(a)||"$direct"},"")};j.prototype.R=function(a){this.B=this.r=a.cookie_expiration;this.pa(a.disable_cookie);this.oa(a.cross_subdomain_cookie)};j.prototype.pa=function(a){(this.disabled=a)&&this.remove()};j.prototype.oa=function(a){if(a!==
this.A)this.A=a,this.remove(),this.save()};d.prototype.s=function(a,b,c){if("undefined"===typeof c)u.error(2,"You must name your new library: init(token, config, name)");else if("mixpanel"===c)u.error(3,"You must initialize the main mixpanel object right after you include the Mixpanel js snippet");else return a=C(a,b,c),r[c]=a,a.m(),a};d.prototype.X=function(a,b,e){this.config={};this.O(c.extend({},L,b,{name:e,token:a,callback_fn:("mixpanel"===e?e:"mixpanel."+e)+"._jsc"}));this._jsc=x();this.D=[];
this.p=[];this.C=t;this.cookie=new j(this.config)};d.prototype.m=function(){this.b("loaded")(this);this.b("track_pageview")&&this.Q()};d.prototype.V=function(){c.a(this.D,function(a){this.n.apply(this,a)},this)};d.prototype.n=function(a,b){if(this.b("img"))return u.error(4,"You can't use DOM tracking functions with img = true."),t;if(!G)return this.D.push([a,b]),t;var c=(new a).s(this);return c.g.apply(c,b)};d.prototype.Y=function(a,b){this.b("test")&&(b.test=1);this.b("img")&&(b.img=1);b._=(new Date).getTime().toString();
a+="?"+c.T(b);if("img"in b){var e=m.createElement("img");e.src=a;m.body.appendChild(e)}else{e=m.createElement("script");e.type="text/javascript";e.async=l;e.defer=l;e.src=a;var d=m.getElementsByTagName("script")[0];d.parentNode.insertBefore(e,d)}};d.prototype.W=function(a){var b,e=[];c.a(a,function(a){a&&(b=a[0],"function"===typeof a?a.call(this):c.isArray(a)&&-1!=b.indexOf("track")&&"function"===typeof this[b]?e.push(a):this[b].apply(this,a.slice(1)))},this);c.a(e,function(a){this[a[0]].apply(this,
a.slice(1))},this)};d.prototype.disable=function(a){"undefined"===typeof a?this.C=l:this.p=this.p.concat(a)};d.prototype.g=function(a,b,e){if("undefined"===typeof a)u.error(5,"No event name provided to mixpanel.track");else if(c.ia()||this.C||c.ga(this.p,a))"undefined"!==typeof e&&e(0);else{b=b||{};b.token=b.za||this.b("token");b.time=c.da();this.d({distinct_id:c.U()},"");this.cookie.S(m.referrer);this.b("store_google")&&this.cookie.ta();this.b("save_referrer")&&this.cookie.ua(m.referrer);var b=c.extend({},
c.info.t(),this.cookie.t(),b),d=c.truncate({event:a,properties:b},255),a=c.l(d),a=c.Z(a);u.log("MIXPANEL REQUEST:");u.log(d);var f=this._jsc,b=this.b("callback_fn");if("undefined"!==typeof e){var h=Math.floor(1E8*Math.random()),b=b+('["'+h+'"]');f[""+h]=function(a){delete f[""+h];e(a,d)}}this.Y(this.b("api_host")+"/track/",{data:a,ip:1,callback:b});return d}};d.prototype.Q=function(a){if("undefined"===typeof a)a=m.location.href;this.g("mp_page_view",c.info.la(a))};d.prototype.sa=function(){return this.n.call(this,
z,arguments)};d.prototype.ra=function(){return this.n.call(this,D,arguments)};d.prototype.e=function(a,b){this.cookie.e(a,b)};d.prototype.d=function(a,b,c){this.cookie.d(a,b,c)};d.prototype.u=function(a){this.cookie.u(a)};d.prototype.fa=function(a){this.cookie.e({distinct_id:a})};d.prototype.ka=function(a){this.cookie.e({mp_name_tag:a})};d.prototype.O=function(a){c.f(a)&&(c.extend(this.config,a),this.cookie&&this.cookie.R(this.config),y=y||this.b("debug"))};d.prototype.b=function(a){return this.config[a]};
d.prototype.ea=function(a){return this.cookie.props[a]};c.toArray=c.k;c.isObject=c.f;c.JSONEncode=c.l;d.prototype.init=d.prototype.s;d.prototype.disable=d.prototype.disable;d.prototype.track=d.prototype.g;d.prototype.track_links=d.prototype.sa;d.prototype.track_forms=d.prototype.ra;d.prototype.track_pageview=d.prototype.Q;d.prototype.register=d.prototype.e;d.prototype.register_once=d.prototype.d;d.prototype.unregister=d.prototype.u;d.prototype.identify=d.prototype.fa;d.prototype.name_tag=d.prototype.ka;
d.prototype.set_config=d.prototype.O;d.prototype.get_config=d.prototype.b;d.prototype.get_property=d.prototype.ea;j.prototype.update_search_keyword=j.prototype.S;j.prototype.clear=j.prototype.clear;if("undefined"===typeof r||"undefined"===typeof r._i)u.error(6,"'mixpanel' object not initialized. Ensure you are using the latest version of the Mixpanel JS Library along with the snippet we provide.");else{var w={};c.a(r._i,function(a){var b;a&&c.isArray(a)&&(b=a[a.length-1],a=C.apply(this,a),w[b]=a)});
var M=function(){c.a(w,function(a,b){"mixpanel"!==b&&(r[b]=a)});r._=c};r.init=function(a,b,c){c?r[c]||(r[c]=w[c]=C(a,b,c),r[c].m()):(c=r,w.mixpanel?c=w.mixpanel:a&&(c=C(a,b,"mixpanel")),window.mixpanel=r=c,M())};r.init();c.a(w,function(a){a.m()});if(m.addEventListener)m.addEventListener("DOMContentLoaded",A,t);else if(m.attachEvent){m.attachEvent("onreadystatechange",A);B=t;try{B=window.frameElement==p}catch(N){}if(m.documentElement.doScroll&&B){var K=function(){try{m.documentElement.doScroll("left")}catch(a){setTimeout(K,
1);return}A()};K()}}c.N(window,"load",A,l)}})(window.mixpanel);
